version: '3.8'

services:
  xhub:
    build: .
    container_name: xhub
    ports:
      - "8866:8866"
    volumes:
      - ./xcookies.txt:/app/xcookies.txt:ro
      - ./logs:/app/logs
    restart: unless-stopped
